# Generated by Django 3.1.14 on 2024-07-11 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_delivery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='product',
        ),
    ]
