# Generated by Django 3.1.14 on 2024-07-11 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20240711_1218'),
        ('cart', '0003_remove_delivery_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='product',
            field=models.ManyToManyField(to='products.Cart'),
        ),
    ]
