# Generated by Django 3.1.14 on 2024-07-11 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_auto_20240712_0019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='product',
        ),
        migrations.AddField(
            model_name='delivery',
            name='product',
            field=models.JSONField(default=12),
            preserve_default=False,
        ),
    ]
