# Generated by Django 3.1.14 on 2024-07-12 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_auto_20240712_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='Phone',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='pincode',
            field=models.CharField(max_length=6),
        ),
    ]
