# Generated by Django 3.1.14 on 2024-07-10 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('price', models.IntegerField()),
                ('details', models.TextField()),
                ('category', models.CharField(max_length=12)),
            ],
        ),
    ]
